version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=mcp_user
      - POSTGRES_PASSWORD=mcp_password
      - POSTGRES_DB=mcp_incidents
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./reports:/app/reports
      - ./mcp/templates:/app/mcp/templates
    restart: unless-stopped

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=mcp_user
      - POSTGRES_PASSWORD=mcp_password
      - POSTGRES_DB=mcp_incidents
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcp_user -d mcp_incidents"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    name: mcp_postgres_data